common_packages:
  - git
  - curl
  - vim
  - btop
  - fish
  - fzf
  - kitty-terminfo

global_hot_dir: "/srv/appdata"
global_cold_dir: "/srv/data"
global_backup_dir: "/srv/backup"
quadlet_dir: "~/.config/containers/systemd"

ansible_ssh_extra_args: "-o SetEnv=TERM=dumb"

paperless_base_dir: "{{ global_hot_dir }}/paperless"
paperless_media_dir: "{{ global_hot_dir }}/paperless/media"
paperless_consume_dir: "{{ global_hot_dir }}/paperless/consume"
paperless_archive_dir: "{{ global_hot_dir }}/paperless/media/documents/archive"
paperless_db_dir: "{{ global_hot_dir }}/paperless/db"
paperless_export_dir: "{{ global_hot_dir }}/paperless/export"
paperless_data_dir: "{{ global_hot_dir }}/paperless/data"
paperless_db_name: "paperless"

nextcloud_data_dir: "{{ global_hot_dir }}/nextcloud/data"
nextcloud_html_dir: "{{ global_hot_dir }}/nextcloud/html"
nextcloud_db_dir: "{{ global_hot_dir }}/nextcloud/db"

immich_upload_dir: "{{ global_cold_dir }}/immich"
immich_base_dir: "{{ global_hot_dir}}/immich"
immich_db_dir: "{{ global_hot_dir }}/immich/db"
