---
nextcloud_domain: "nextcloud.{{ vault_base_domain }}"
nextcloud_trusted_domains: "{{ vault_nextcloud_trusted_domains }}"
nextcloud_overwrite_protocol: "https"
nextcloud_timezone: "Europe/Amsterdam"
