version: "3.9"
services:
  it-tools:
    image: "docker.io/corentinth/it-tools:latest"
    labels:
      - "io.containers.autoupdate=registry"
    container_name: it-tools
    restart: unless-stopped
    ports:
      - "8081:80"
