---
restic_repos:
  local: "{{ global_backup_dir }}/restic"
  gdrive: "rclone:gdrive:restic"

restic_paths:
  - "{{ nextcloud_data_dir }}"
  - "{{ paperless_export_dir }}"
# ExecStartPre=/usr/bin/podman exec paperless-server document_exporter /usr/src/paperless/export --delete --no-archive --no-thumbnail

restic_excludes:
  - "{{ nextcloud_data_dir }}/appdata_*/preview"

restic_retention:
  nextcloud: { keep-daily: 30, keep-monthly: 12 }
  immich: { keep-daily: 14, keep-monthly: 6 }
  paperless: { keep-daily: 30, keep-monthly: 12 }
  infra: { keep-daily: 14, keep-monthly: 6 }
  db: { keep-daily: 30, keep-monthly: 12 }
