---
authelia_version: "4.39.20"
authelia_domain: "auth.{{ vault_base_domain }}"
authelia_cookie_domain: "{{ vault_base_domain }}"
authelia_url_protocol: "https"

authelia_port: 9091
authelia_manage_users: true

authelia_session_expiration: "1h"
authelia_session_inactivity: "5m"
authelia_session_remember_me: "1M"

authelia_access_rules:
  - { domains: ["it-tools.{{ authelia_cookie_domain }}"], policy: one_factor }
  - { domains: ["uptime.{{ authelia_cookie_domain }}"], policy: one_factor }
