all:
  children:
    homeservers:
      fedora-server:
        ansible_host: "{{ vault_server_host }}"
        ansible_user: jpklindt
        backup_drive_path: "/dev/disk/by-id/{{ vault_backup_disk_serial }}"
        data_drive_path: "/dev/disk/by-id/{{ vault_data_disk_serial }}"
    workstations:
      vars:
        ansible_connection: local
      hosts:
        fedora-desk:
        fedora-flex:
