all:
  children:
    homeservers:
      hosts:
        fedora-vagrant:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: vagrant
          backup_drive_path: /dev/vdc
          data_drive_path: /dev/vdb
