---
- name: Ensure user unit directory exists
  ansible.builtin.file:
    path: "{{ user_unit_dir }}"
    state: directory
    mode: "0755"

- name: Copy user units
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ user_unit_dir }}/{{ item }}"
    mode: "0644"
  loop: "{{ user_unit_files }}"
  register: user_units_copied

- name: Reload user manager
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  when: user_units_copied is changed
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_effective_user_id }}"

- name: Enable user timers
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
    scope: user
  loop: "{{ user_unit_enable }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_effective_user_id }}"
