
# nvim integration
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n C-j if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n C-k if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n C-l if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

# globals
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -sg escape-time 10
set -g default-terminal "tmux-256color"
set -g default-shell /usr/bin/fish
set-option -sa terminal-overrides ",xterm*:Tc"

# Prefix
set -g prefix C-space
unbind C-b
bind C-Space send-prefix
bind C-l send-keys 'C-l'

# copy paste

setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Splits
bind '\' split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
unbind '"'
unbind % 

bind s switch-client -T split-table
bind -T split-table h split-window -v -c "#{pane_current_path}"
bind -T split-table v split-window -h -c "#{pane_current_path}"
bind -T split-table x kill-pane

# Resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-yank'        # Cross-platform support for clipboard.
set -g @plugin 'tmux-plugins/tmux-resurrect'   # Save/Restore sessions
set -g @plugin 'tmux-plugins/tmux-continuum'   # Auto Save/Restore

set -g @sessionx-bind 'o'
set -g @continuum-restore 'on'

# Auto dark mode
run-shell 'hour=$(date +%H); \
  if [ "$hour" -ge 7 ] && [ "$hour" -lt 19 ]; then \
    tmux set -g @catppuccin_flavor "latte"; \
  else \
    tmux set -g @catppuccin_flavor "mocha"; \
  fi'

set -g @catppuccin_window_status_style "none"

run '~/.config/tmux/plugins/tmux/catppuccin.tmux'

# Status bar
set -g status-position bottom
set -g status-justify left
set -g status-left-length 100
set -g status-right-length 100
set -g window-status-separator ""

set -g status-left "#[fg=#{@thm_crust},bg=#{?client_prefix,#{@thm_red},#{@thm_green}},bold] #{@catppuccin_session_icon} #S #[fg=#{?client_prefix,#{@thm_red},#{@thm_green}},bg=#{@thm_mantle},nobold]"

set -g window-status-format "#[fg=#{@thm_overlay_0},bg=#{@thm_mantle}] #I #W#{?window_zoomed_flag, 󰁌,} "
set -g window-status-current-format "#[fg=#{@thm_mantle},bg=#{@thm_surface_1}]#[fg=#{@thm_lavender},bg=#{@thm_surface_1},bold] #I #W#{?window_zoomed_flag, 󰁌,} #[fg=#{@thm_surface_1},bg=#{@thm_mantle},nobold]"

set -gF window-status-activity-style "fg=#{@thm_yellow},bg=#{@thm_mantle}"
set -gF window-status-bell-style "fg=#{@thm_red},bg=#{@thm_mantle}"

set -g status-right "#[fg=#{@thm_surface_0},bg=#{@thm_mantle}]#[fg=#{@thm_fg},bg=#{@thm_surface_0}] #{@catppuccin_directory_icon} #{b:pane_current_path} "
set -ag status-right "#[fg=#{@thm_surface_1},bg=#{@thm_surface_0}]#[fg=#{@thm_fg},bg=#{@thm_surface_1}] #{@catppuccin_date_time_icon} %H:%M "
set -ag status-right "#[fg=#{@thm_blue},bg=#{@thm_surface_1}]#[fg=#{@thm_crust},bg=#{@thm_blue},bold] #h "

# Install tpm
if "test ! -d ~/.config/tmux/plugins/tpm" \
  "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm \
    && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

run '~/.config/tmux/plugins/tpm/tpm'
