#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/paperless

- name: Create paperless storage directories
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ vault_admin_username }}"
    group: "{{ vault_admin_username }}"
  loop:
    - "{{ global_hot_dir }}/paperless/"
    - "{{ paperless_db_dir }}"
    - "{{ paperless_export_dir }}"
    - "{{ paperless_media_dir }}"
    - "{{ paperless_archive_dir }}"
    - "{{ paperless_data_dir }}"
    - "{{ paperless_consume_dir }}"

- name: Share storage directories with Nextcloud
  become: true
  become_method: containers.podman.podman_unshare
  changed_when: false
  ansible.builtin.file:
    path: "{{ item }}"
    owner: 33
    group: 33
  loop:
    - "{{ paperless_media_dir }}"
    - "{{ paperless_consume_dir }}"
    - "{{ paperless_export_dir }}"
    - "{{ paperless_data_dir }}"

- name: Deploy paperless quadlets
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/quadlet.yml"
  vars:
    quadlet_service: paperless-pod.service
    quadlet_files:
      - paperless.pod
      - paperless-redis.container
      - paperless-gotenberg.container
      - paperless-tika.container
    quadlet_templates:
      - paperless-server.container
      - paperless-db.container
