---
# tasks file for roles/paperless
- name: Create Paperless base directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ paperless_base_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ vault_admin_username }}"
    group: "{{ vault_admin_username }}"

- name: Create paperless storage directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ paperless_db_dir }}"
    - "{{ paperless_export_dir }}"
    - "{{ paperless_media_dir }}"
    - "{{ paperless_archive_dir }}"
    - "{{ paperless_data_dir }}"
    - "{{ paperless_consume_dir }}"

- name: Share storage directories with Nextcloud
  become: true
  become_method: containers.podman.podman_unshare
  ansible.builtin.file:
    path: "{{ item }}"
    owner: 33
    group: 33
  loop:
    - "{{ paperless_media_dir }}"
    - "{{ paperless_consume_dir }}"
    - "{{ paperless_export_dir }}"
    - "{{ paperless_data_dir }}"

- name: Deploy paperless quadlets
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/quadlet.yml"
  vars:
    quadlet_service: paperless-pod.service
    quadlet_files:
      - paperless.pod
      - paperless-redis.container
      - paperless-gotenberg.container
      - paperless-tika.container
    quadlet_templates:
      - paperless-server.container
      - paperless-db.container

- name: Deploy backup services
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/user_units.yml"
  vars:
    user_unit_files: [paperless-export.service]
