caddy_base_domain: "127.0.0.1.nip.io"

nextcloud_domain: "nextcloud.{{ caddy_base_domain }}"
nextcloud_trusted_domains: "nextcloud.{{ caddy_base_domain }}"
nextcloud_overwrite_protocol: "http"

paperless_domain: "paperless.{{ caddy_base_domain }}"
paperless_allowed_hosts: "paperless.{{ caddy_base_domain }},localhost,127.0.0.1"
paperless_overwrite_protocol: "http"
