# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/nextcloud

- name: Create Nextcloud base directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ global_hot_dir }}/nextcloud"
    state: directory
    mode: "0755"
    owner: "{{ vault_admin_username }}"
    group: "{{ vault_admin_username }}"

- name: Create Nextcloud storage directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    # mode: "0755"
  loop:
    - "{{ nextcloud_data_dir }}"
    - "{{ nextcloud_html_dir }}"
    - "{{ nextcloud_db_dir }}"

- name: Own data and html dirs as container www-data
  become: true
  become_method: containers.podman.podman_unshare
  ansible.builtin.file:
    path: "{{ item }}"
    owner: 33
    group: 33
  loop:
    - "{{ nextcloud_data_dir }}"
    - "{{ nextcloud_html_dir }}"


- name: Copy static quadlet files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/.config/containers/systemd/{{ item }}"
    mode: "0644"
  loop:
    - nextcloud.pod
    - nextcloud-valkey.container
    - nextcloud-cron.timer
  notify: Reload systemd

- name: Template quadlet files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "~/.config/containers/systemd/{{ item }}"
    mode: "0644"
  loop:
    - nextcloud-cron.container
    - nextcloud-database.container
    - nextcloud-server.container
  notify:
    - Reload systemd
    - Restart nextcloud server

- name: Start Nextcloud pod
  ansible.builtin.systemd:
    name: nextcloud-pod.service
    state: started
    enabled: true
    scope: user
    daemon_reload: true
