---
# tasks file for roles/immich

- name: Create Immich storage directories
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ vault_admin_username }}"
    group: "{{ vault_admin_username }}"
  loop:
    - "{{ immich_upload_dir }}"
    - "{{ immich_db_dir }}"

- name: Deploy immich quadlets
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/quadlet.yml"
  vars:
    quadlet_service: immich-pod.service
    quadlet_files: [immich.pod, immich-redis.container]
    quadlet_templates:
      - immich-server.container
      - immich-database.container
      - immich-machine-learning.container
