---
# tasks file for roles/immich

- name: Create Immich storage directories
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ vault_admin_username }}"
    group: "{{ vault_admin_username }}"
  loop:
    - "{{ immich_upload_dir }}"
    - "{{ immich_db_dir }}"

- name: Copy static quadlet files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.config/containers/systemd/{{ item }}"
    mode: "0644"
  loop:
    - immich.pod
    - immich-redis.container
  notify: Reload systemd

- name: Template quadlet files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ lookup('env', 'HOME') }}/.config/containers/systemd/{{ item }}"
    mode: "0644"
  loop:
    - immich-server.container
    - immich-database.container
    - immich-machine-learning.container
  notify: Reload systemd

- name: Start Immich pod
  ansible.builtin.systemd:
    name: immich-pod.service
    state: started
    enabled: true
    scope: user
    daemon_reload: true
