no_display=1
toggle_hud=Shift_R+F12

legacy_layout=false

# CPU
cpu_stats
cpu_temp
cpu_mhz
cpu_power
core_load
core_load_change
core_bars

# GPU
gpu_stats
gpu_temp
gpu_core_clock
gpu_mem_clock
gpu_power
gpu_fan
throttling_status

# Memory
ram
vram
swap
procmem

# Frame data
fps
frametime
frame_timing
fps_color_change

# Context
gpu_name
engine_version
vulkan_driver
resolution

font_size=20
position=top-right
background_alpha=0.5
round_corners=8

