---
- name: Base Configuration
  hosts: all
  roles:
    - base

- name: Storage Configuration
  hosts: homeservers
  roles:
    - storage

- name: Deploy Apps
  hosts: homeservers
  become: true
  become_user: "{{ vault_admin_username }}"

  roles:
    - infra
    - immich
    - apps
