---
- name: Base Configuration
  hosts: homeservers
  roles:
    - role: base
      tags: [base]
    - role: devsec.hardening.ssh_hardening
      become: true
      tags: [base, ssh]
      vars:
        ssh_client_hardening: false
        ssh_max_auth_retries: 6
    - role: notify
      become: true
      tags: [base, notify]
    - role: tailscale
      become: true
      tags: [base, tailscale]

- name: Storage Configuration
  hosts: homeservers
  roles:
    - role: storage
      tags: [storage]

- name: Deploy Apps
  hosts: homeservers
  become: true
  become_user: "{{ vault_admin_username }}"
  pre_tasks:
    - name: Ensure quadlet directory exists
      ansible.builtin.file:
        path: "~/.config/containers/systemd"
        state: directory
        mode: "0755"
      tags: always

  roles:
    - role: caddy
      tags: [infra, caddy]
    # - role: immich
    #   tags: [services, immich]
    - role: apps
      tags: [services, it-tools, apps]
    - role: paperless
      tags: [services, paperless]
    - role: nextcloud
      tags: [services, nextcloud]
    - role: restic
      tags: [backup, restic]
    - role: gtnh_backup
      tags: [backup, gtnh]
