---
- name: Base Configuration
  hosts: homeservers
  roles:
    - role: base
      tags: [base]

- name: Storage Configuration
  hosts: homeservers
  roles:
    - role: storage
      tags: [storage]

- name: Deploy Apps
  hosts: homeservers
  become: true
  become_user: "{{ vault_admin_username }}"
  pre_tasks:
    - name: Ensure quadlet directory exists
      ansible.builtin.file:
        path: "~/.config/containers/systemd"
        state: directory
        mode: "0755"
      tags: always

  roles:
    - role: caddy
      tags: [infra, caddy]
    - role: uptime_kuma
      tags: [infra, uptime_kuma]
    - role: immich
      tags: [services, immich]
    - role: apps
      tags: [services, it-tools, apps]
    - role: paperless
      tags: [services, paperless]
    - role: nextcloud
      tags: [services, nextcloud]
